### ISSUE TITLE
Suggestion - "grid" as split type

### ISSUE THREAD

**Issue by bradparks** [mhinz/vim-startify#140]
hey! I like this alot ;-) Great work!

I've been trying to see if there's an easy way for me to select a series of files from the start screen, and have them ultimately displayed in a grid.

For example, just say there were 4 files that I wanted to select, and show in a 2x2 grid. Is there a way to do this? 

If not, perhaps a new type of split could be created, one called "grid" or (g) as a shortcut. You'd just go through the startup screen, and specify in order the files you wanted shown in your grid. It'd open them in the grid positions 0,1,2,3 they were selected in....

```
0 | 1
------
2 | 3
```

Of course if 5 files were picked, it'd break it into a 3x2 grid, etc. Do you think this is possible?

Thanks!

**Comment by mhinz** [comment]
Hi, and sorry for the belated response.

With enough time thrown at it, this would certainly possible, but honestly I don't think such a complex implementation would be worth the effort.

Layouting the text would be the easier task, but then cursor placement (which is kind of trickier than most people would expect due to many corner cases) and highlighting rules would have to be completely rewritten.

Let's keep things simple. :-)

Thanks for bringing this up anyway!

**Comment by bradparks** [comment]
hey! no prob! thanks for the great tool... i use it everyday!

**Comment by mhinz** [comment]
I'm glad to hear that. :-)
