### ISSUE TITLE
Autoloading session in current working directory

### ISSUE THREAD

**Issue by hlin117** [mhinz/vim-startify#142]
Suppose I have a directory X, where I previously saved a session. 

It'd be nice if there were an option where if you typed `vim` within directory X, vim would automatically load the session saved in directory X. (IE: It'd be nice to circumvent the start screen.)

Thoughts?

**Comment by mhinz** [comment]
`:h g:startify_sesssion_autoload`. Like this? :)

**Comment by hlin117** [comment]
Hmm, I thought that was the option, but when I tried setting it to 1, it didn't work.

My .bashrc is <a href=https://github.com/hlin117/dotfiles/blob/master/.vimrc#L115>here</a>, and I'm setting it to 1 on line 115.

I verified using `:let g:` that `startify_session_autoload`'s value was set to 1. I also created a <a href="https://github.com/hlin117/dotfiles/blob/master/.vim/session/colors">session</a> within my <a href=https://github.com/hlin117/dotfiles/tree/master/.vim/colors>~/.vim/colors folder</a>, and it doesn't seem to be working.

Thoughts?

**Comment by mhinz** [comment]
Oh, I forgot that it was working a bit differently. A `Session.vim` should be shown as entry `[0]` in the startify buffer:
![foo](http://i.imgur.com/yfbHMI5.png)
So loading the session just takes another hit of <kbd>Enter</kbd> which, in my opinion, is a good compromise, since there might be use cases where you simply forgot that a `Session.vim` was present and didn't want `$ vim` to load it right away.

`g:startify_session_autoload` only takes effect when opening a bookmarked directory. I'll change that!

**Comment by hlin117** [comment]
Thank you! I'll look forward to the commit.

**Comment by mhinz** [comment]
Hopefully it works as expected now!

**Comment by hlin117** [comment]
Yup, it works. Admittedly though, it took a tad to figure out, since I had to change the `g:startify_session_autoload = "."`, and save my session as `Session.vim` (instead of some other name).

I believe this is intentional though. Excellent work.

**Comment by mhinz** [comment]
I changed the docs, so it's all explained in `:h g:startify_session_autoload`. Better just set it to `1` instead of `".", though. :-)

Thanks for pointing out this issue.

**Comment by hlin117** [comment]
You're right; I meant to say that I made `g:startify_session_dir = '.'`, my mistake.
