### ISSUE TITLE
Support CtrlP's MRU mechanism

### ISSUE THREAD

**Issue by andrewferrier** [mhinz/vim-startify#148]
vim-startify is a great plugin, but it uses the same MRU mechanism as standard vim (i.e. the viminfo file), not the ~/.cache/mru/cache.txt information used by CtrlP. This leads to an inconsistency between the files listed by :CtrlPMRU and vim-startify. It would be great if vim-startify had an option to use CtrlP's cache instead.

If I get some time, I might look at creating a patch for this, but would welcome your comments.

**Comment by mhinz** [comment]
I never really used ctrlp, but I'm looking into it.

**Comment by mhinz** [comment]
I merged that into master now. Tell me if it works good enough for you.

**Comment by andrewferrier** [comment]
I'm a little confused; the last changes on master seem to be 9 days ago? Not sure what you've changed?

To answer your previous question, I don't think it's quite that simple. Something strange is certainly going on for me. When I open vim with vim-startify, typically I'm only seeing one file in the recent files list, even though my ~/.vim/.viminfo shows 10 file marks and I've been using vim for some time (so you'd expect loads of recently used files - I assume it's the section marked "File marks: " which is relevant, correct?). So even ignoring CtrlP, something isn't right.

In fact, I think I may have figured out (partly) what's going on. Although I configure a different location for my .viminfo in my ~/.vimrc:

```
set viminfo='20,s10,/20,:50,h,n~/.vim/.viminfo
```

it seems that vim-startify ignores that and uses ~/.viminfo instead. I think vim ignores that when it writes to .viminfo and writes to mine, though. I think that may be causing the inconsistency I'm seeing.

Any thoughts?

**Comment by mhinz** [comment]
The only time the plugin interacts with viminfo is by reading the internal variable `v:oldfiles` (`:echo v:oldfiles`). That variable gets filled at start and the viminfo file gets written at exit of Vim. So, when you opened some files and called `:Startify`, you wouldn't see the most recently opened files, because `v:oldfiles` doesn't get updated on-the-fly. The latest commit (was commited 9 days ago in a testing branch and merged into master yesterday) kind of fixes that issues by prepending newly opened files to `v:oldfiles`, so `:Startify` should always show the real recently used files.

**Comment by mhinz** [comment]
Feel free to reopen, if you think there is something that should be changed in the plugin. :)
