### ISSUE TITLE
Per-tab sessions

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-startify#150]
It would be a great feature to have option to treat new tabs in Vim like new sessions. Instead of using `cd` to switch working directory when this option is enabled `lcd` should be used. This would ensure each tab has it's own working directory and since buffer restore and window layout come after restoring path everything should work without too much effort.

Also, on `TabNew` event new Startify window should be opened if this feature is turned on.

**Comment by mhinz** [comment]
1) There is no `TabNew` event in Vim, but there's `TabNewEntered` in nvim. See https://github.com/mhinz/vim-startify/issues/139
_2_) When you say session do you mean _Vim instance_ or really a _Vim session_ (as in `:mksession`)? The latter would be hard to achieve in Vim, because of Startify's session persistence feature.

**Comment by MeanEYE** [comment]
Good point. I just did little experimentation in past few days and indeed it's not all that flexible as I originally thought. While `lcd` does indeed allow per-tab working directory it's not all straight forward. I'd mark this as closed as it's not something easily done. Creates more problems than it solves.

**Comment by mhinz** [comment]
Okey-dokey. Thanks for the feedback nevertheless!
