### ISSUE TITLE
Grouped bookmarks

### ISSUE THREAD

**Issue by pablasso** [mhinz/vim-startify#151]
I don't really care for last opened files or current files in the directory, what I would like to do is to have different bookmarks grouped by titles. i.e:

      Work:
    [0] something a
    [1] something b

      Personal:
    [2] something c
    [3] something d

I haven't figured out a way to do it. Is that possible?

**Comment by mhinz** [comment]
Currently that's not possible. I'll see if I can come up with a nice way to implement it!

**Comment by pablasso** [comment]
If you give me some guidance maybe I could provide a PR.

**Comment by mhinz** [comment]
Oh, sorry, somehow I missed your response. Let's see..

- startify calls `insane_in_the_membrane()` *lots of init stuff happens*
- the actual "list view" happens in this loop: https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L104-L111
  - above the code you see the default definition of `s:lists` (in case you don't have `g:startify_lists` set)
- the loop is a bit of a hack, but that's VimL for you :-)
  - if the current element is a string (`type(elem) == 1`), then it's either `dir`/`files`/`sessions` or `bookmarks` -> `s:show_dir`/`s:show_files` etc. gets called
  - if it's not a string, it must be a list of strings (by convention) and eventually gets called by `s:print_section_header()` at the head of the `s:show_*` functions

So, currently, we can have only one bookmark list (because `s:show_bookmarks` simply loops over `g:startify_bookmarks`.

Now the question is how to add an arbitrary number of bookmark lists, without breaking backwards compatability.

**Comment by pablasso** [comment]
Thanks a lot! I'll take a look.

**Comment by mhinz** [comment]
If you come around to have an idea about this one, please just reopen this issue. Thanks!

**Comment by charliesbox** [comment]
@pablasso how is the PR going?
