### ISSUE TITLE
Navigation on the lists can't go past wrapped text if using ":map j gj"

### ISSUE THREAD

**Issue by viccuad** [mhinz/vim-startify#156]
Well, I think the says it all. 

To reproduce:
1. Issue an `:map j gj` 
2. I have the following relevant options:
    
    set wrap
    set linebreak		
    set breakindent
    set formatoptions=tcrql 

resize your vim terminal window to something thin enough so wrapping happens, 

    [0]  ~/.vimrc
    [1]  ~/.vimlog
    [2]  ~/.dotfiles/
    vim/.vimrc
    [3]  ~/install.sh

And you will notice that pressing "j" you can't go from [2] to [3].

**Comment by mhinz** [comment]
First off, thanks for reporting.

`gj` tries to go one display line down, but Startify has some autocmds in effect, so that the `[x]` can never be left. The cursor actually goes down but jumps back immediately. Vim is just clever enough not to redraw the screen in between, so one can't see it.

The easiest solution would be to just force some new and local mappings in the Startify buffer, e.g.:

```vim
if mapcheck('j', 'n')
  nunmap j
endif
```

I'll see if I can come up with other approaches, otherwise I'll do just this.

**Comment by mhinz** [comment]
It should be fixed now.

**Comment by viccuad** [comment]
Awesome! many thanks!

**Comment by mhinz** [comment]
:shipit:
