### ISSUE TITLE
encrypted file error to open

### ISSUE THREAD

**Issue by winsphinx** [mhinz/vim-startify#162]
when open a file encrypted by :X, 
if just press the pilot number, it will open correctly, (as usual vim is waiting for inputting encrypted code);
but if move cursor to the file and press <cr> or mouse click it, it will open in encrypted unreadable characters.

**Comment by mhinz** [comment]
Hmm, it works for me. Don't you get any error messages? (Check with `:messages`.)

**Comment by winsphinx** [comment]
I tested in gvim7.4 under win7 & win10, and in vim7.3 under archlinux, that appears every times. And no error messages output.
Commenting that 2 lines doesnot work.
Here is my steps:
1. Start gvim and :e ~/testfile, then insert some words;
2. Press :X and input passcode twice, then :wq to save and quit gvim;
3. Restart gvim, ~/testfile may be listed in the first line of MRU, then mouse double click it -- the file opens directly without tip of waiting for the passcode, and shows unreadable words.

**Comment by mhinz** [comment]
Well, I can reproduce that, but the important bit is that you should get an error (check `:messages`) like this:

`E832: Non-encrypted file has encrypted undo file: /Users/mhi/.vim/files/undo/%private%tmp%testfile`

Because if this is happening, I could simply catch the error and issue `:edit` which will ask for the key properly.

**Comment by mhinz** [comment]
See if it's working for you in the latest commit.

**Comment by winsphinx** [comment]
It works perfectly both on windows and linux.
Thanks for you great work.

**Comment by mhinz** [comment]
Thanks for reporting. :-)
