### ISSUE TITLE
option to not change the working directory

### ISSUE THREAD

**Issue by benjumanji** [mhinz/vim-startify#171]
Hi, from what I can see in #11 (and observed behaviour when using startify) when selecting a file the working directory is changed to that of the file opened. This is really subotimal for people that open their vim at the project root and don't expect that to change (for instance it makes Unite's file_rec search useless if you switched to a leaf directory). Would it be possible to have an option to not change directory?

**Comment by mhinz** [comment]
Hi,

see `:h g:startify_change_to_dir` and `:h g:startify_change_to_vcs_root`.

**Comment by benjumanji** [comment]
I sear I read the help 3 times looking for that setting. I suck! Thank you for pointing that out.

**Comment by mhinz** [comment]
:-)

**Comment by andrewheartsxd** [comment]
Sorry to resurrect this, but when I open a session, even with `g:startify_change_to_dir` and `g:startify_change_to_vcs_root` set, I'm still in the file's working directory. Is there any option for keeping me at the project root when opening a session?

**Comment by mhinz** [comment]
When you source a session, either by choosing it from the Startify menu or using `:SLoad` directly, the options `g:startify_change_to_dir` and `g:startify_change_to_vcs_root` don't matter.

So, you should be at the same directory as when you used `:SSave` to create the session. And make sure that you didn't alter `:h sessionoptions`. When you `:echo &ssop`, it should contain `curdir`.

**Comment by andrewheartsxd** [comment]
I just tried again and it's working fine. Thanks for the reply (and the awesome plugin)!

**Comment by Jeppelelle** [comment]
> So, you should be at the same directory as when you used `:SSave` to create the session

Is that true with "let g:startify_session_persistence = 1" too? I can't get it to work as i expect:

If i: "cd /Volumes/www/dev/test/root", then nvim, then `:SSave` Test

In my Test session file i will get the proper "cd /Volumes/www/dev/test/root"

After that, opening nerdtree, doing FzF :Files etc etc, all of them will use the "root" directory as the working directory as expected

However, whats not expected: if i open a file after that: "absolutelynotroot/notInRoot.php", then :q out of nvim, my session file will now have changed it's "cd" path to "cd /Volumes/www/dev/test/root/absolutelynotroot"

Next time i open the "Test" session my working directory will now be "absolutelynotroot" instead of "root" so all my FzF searches will work from "absolutelynotroot" instead of "root", ripgrep `:Rg` is also now "broken" since it's in the wrong working directory

I can fix the issue by opening up nerdtree, go back 1 directory to "root" again, press C & now all my FzF & :Rg works properly again

Thats not a good workaround, i thought setting "g:startify_change_to_dir = 0" would NEVER EVER change the "cd" directory in the session file to anything other than the directory that was set on the first `:SSave`?
