### ISSUE TITLE
How to reference currenty startify loaded session

### ISSUE THREAD

**Issue by steadystatic** [mhinz/vim-startify#181]
I'm trying to use tmux-resurrect and wanted to autosave the session on VimLeave like this in my .vimrc:

`function SaveBeforeShutdown()
  " Some call to startify here to
  " A. check if it's a session
  " B. If it is a session, save it
endfunction
au VimLeave * call SaveBeforeShutdown()`

I've enabled these flags for vim-startify:
`let g:startify_session_persistence = 1`
`let g:startify_session_autoload = 1`

Is there a way to reference if vim-startify has a session it loaded named in a string variable someplace? I looked at startify.vim +201 and saw v:this_session ?

I'm trying to figure this out for myself and another tmux-resurrect/vim-startify lover here: https://github.com/tmux-plugins/tmux-resurrect/issues/107

Thanks as always for this awesome plugin :+1:

**Comment by mhinz** [comment]
Hi. I was away for the last 2 months so I have to read up on many things right now.

I'm not sure I'm getting the whole picture at the moment, but yes, you can always check `v:this_session` (see `:h v:this_session`). It's a builtin variable but can be set by users. If there is a running session, that variable will contain its name.

`g:startify_session_persistence` will also work on `VimLeave`, so pay attention to when your autocmd is set, since autocmds are executed in the order they were given.

> Thanks as always for this awesome plugin

:-)

**Comment by mhinz** [comment]
`:SLoad` without an argument loads the last used session now (on non-Windows).

Session persistence + tmux-resurrect are a dream team now:

```tmux
set -g @resurrect-processes '"vim->vim +SLoad"'
```
