### ISSUE TITLE
Default menu item is no longer set to [e]mpty

### ISSUE THREAD

**Issue by kapsh** [mhinz/vim-startify#212]
It looks like quotes feature broke default menu item on startify screen. 

Check this screenshot. In older revision 8434c33 default was set to empty buffer, but in a4d8870 it is set to first of MRU. I think this is completely ruins ux pattern "open vim without filename, quick press enter, type". 
![image](https://cloud.githubusercontent.com/assets/144717/14014343/fc25822e-f1c2-11e5-8942-83d5ca1dfb3a.png)

**Comment by mhinz** [comment]
Actually the bug was that it was ever set at `[e]`. It works if you use `g:startify_list_order = ['files']` to avoid the section headers. The cursor was always meant to be at `[0]` except when there was a local `Session.vim` found.

Anyway, for simplicity purposes I'll make the cursor always jump to the first entry now. People who don't want to be at `[e]` by default, can simply use `g:startify_enable_special = 0` in that case.

**Comment by mhinz** [comment]
It should work now.

**Comment by kapsh** [comment]
Oh, right, it works as expected. Thank you.

**Comment by mhinz** [comment]
Great, thanks for mentioning this inconsistency!
