### ISSUE TITLE
Clearing out my path when I open Java files

### ISSUE THREAD

**Issue by mvittiglio** [mhinz/vim-startify#213]
Hey mhinz, 
This plugin is simply awesome but I'm sad to say that for some reason it clears out my path variable and makes commands like 'gf' unusable. I've had to disable but if I'm doing something stupid please LMK.

**Comment by mhinz** [comment]
Hi,

sorry for the late response, but I was away from computers for a while.

I can't think of any way this plugin could clear the `'path'` option, though. I don't think the issue is related to this plugin directly. Please provide provide minimal steps for reproducing it.

(Please reopen, if you still think it's a problem in the plugin itself.)
