### ISSUE TITLE
buftype=nofile causes quickfix to not use startify buffer

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-startify#214]
When opening an entry from a quickfix list below the startify buffer, Vim won't reuse a `nofile` buffer apparently.

TEST CASE:
1. Open vim, with startify
2. `grep! . *`
3. `:copen`
4. Press Enter

A new (thrid) window is opened to show the result, whereas the startify window should be used.

Removing this setting fixes it.

I have tried `buftype=nowrite` also, with the same result.

```diff
diff --git a/autoload/startify.vim b/autoload/startify.vim
index 990d0df..3759e28 100644
--- a/autoload/startify.vim
+++ b/autoload/startify.vim
@@ -54,7 +54,6 @@ function! startify#insane_in_the_membrane() abort
 
   setlocal
         \ bufhidden=wipe
-        \ buftype=nofile
         \ nobuflisted
         \ nocursorcolumn
         \ nocursorline
```

	nofile only:	The buffer name is fixed, it is not handled like a
			file name.  It is not modified in response to a |:cd|
			command.

**Comment by blueyed** [comment]
See also https://github.com/vim/vim/issues/516.

**Comment by mhinz** [comment]
The problem is pretty old and the value of `buftype` changed a few times in the beginning, since both variants had disadvantages.

See https://github.com/mhinz/vim-startify/issues/6 and `h startify-faq-05`. The [last time it was changed](https://github.com/mhinz/vim-startify/commit/53019cc309c3bc165e04c1a092832500ce41ae92), I apparently forgot to state why..

Well, I'll change it and see how it works out. Thanks for bringing it up again.
