### ISSUE TITLE
option to launch neovim terminal from startup page

### ISSUE THREAD

**Issue by rockneverdies55** [mhinz/vim-startify#215]
Would be nice to have if the plugin had an option to quickly launch neovim terminal *(if available)* from within the startup page.

**Comment by wsdjeg** [comment]
why do not add some thing to bashrc?
for example
aliase nvimt='nvim +terminal'

than you can just use vimt

**Comment by Alok** [comment]
```
    autocmd User Startified nnoremap <buffer> r :terminal<CR>
```

I find this works fine. You can of course change the mapping ( `t` is already reserved to mark files to be opened in a new tab and `r` reminds me of `r'EPL, plus `r`'s regular function doesn't work in the startify buffer.)

**Comment by wsdjeg** [comment]
:+1:

**Comment by mhinz** [comment]
Yup, either use the User autocmd as described above or use the this new option: `:h g:startify_commands`.

Since you want it displayed only if it's available, you could do something like this:

```vim
let g:startify_commands = []
if exists(':terminal') == 2
  call add(g:startify_commands, ['Funky Neovim Terminal', 'term'])
endif
```

In Vim's case, the list will be empty and Startify won't bother. Should be exactly what you're looking for!
