### ISSUE TITLE
Cannot "find next" when searching

### ISSUE THREAD

**Issue by protist** [mhinz/vim-startify#218]
If I search for a string, the cursor moves to the "clickable" index for the line that contains the string. e.g. given the following list
```
[1] foo_a
[2] bar
[3] foo_b
```
searching for `foo` will find it in `foo_a`, and move the cursor to the `1`. If I hit `n` to find the next occurrence, it will never progress to `3`. Presumably this is because it finds the next `foo` (again in `foo_a`), which is on that same line, and automatically moves the cursor back to the `1`.

**Comment by mhinz** [comment]
> Presumably this is because it finds the next `foo` (again in `foo_a`), which is on that same line, and automatically moves the cursor back to the `1`.

That's the exact issue, unfortunately I don't know how to work around this without giving up the current implementation of the "menu". A lot of code relies upon the cursor always being on the indices.

**Comment by mhinz** [comment]
Well, maybe I will change the way the menu works in the future, so I let this open.

**Comment by protist** [comment]
Thanks for the reply. I don't really know enough about vim's remapping or how specific it can be, but could you rebind `n`? Something like `j` then `n` would work if there were at least one match in the buffer, but would give unexpected results if there were none. Instead of `j`, I'm not sure if you could temporarily move to the end of the line, or if startify would pull you back to the index? This would give expected results when there were no matches.

Also, this remapping would have to be reverted when leaving startify. I'm not sure if that's possible either.

**Comment by mhinz** [comment]
Right. Remapping `n`/`N` would work. Reverting wouldn't be a problem either, since the mappings could simply be made local to the buffer only.

A few caveats though:

1. [There might be people who remap these keys already](https://github.com/mhinz/dotfiles/blob/55290c69a2c14bd78f3cbb4350d0da41204673a5/vim/vimrc#L243-L244). That will be a small minority, though.

2. The other "issue" you mentioned, that `n` would do the `j`, even if there wasn't a match, is true, but I think most people won't use `n` anyway when `/` failed already. (One could work around this with a small function that calls `:h search()`, but I'd prefer not doing so in favour of the more simple solution.)

3. If the custom header (whose lines can never be reached) contains the search text, one will never be able to wrap around to the last match with `N`.

All in all, there's no perfect solution and none of the mentioned issues is a deal breaker, that's why I opt for the simple solution of remapping which probably does what most people expect it to be.

**Comment by mhinz** [comment]
Please see if the latest commit makes it work for you.

**Comment by protist** [comment]
Thanks @mhinz! It works great! Of course, once installed, I went about trying to test the caveats you listed, and trying to break it… :stuck_out_tongue:

I also get strange results when I search other "non-selectable" things, in addition to the header/footer, such as the subheadings `Recent files`. However, I think that oddness is reasonable. The other strange thing occurs when searching for strings in the index itself, e.g. `\[`, but now I think I'm just being perverse. :flushed:

Apart from me being stupid and trying to break it, I think it works perfectly. If the search finds text in the main paths, then it does what is expected. Thank you for the quick fix and replies!

**Comment by mhinz** [comment]
Thank you for bringing it up! 👍
