### ISSUE TITLE
Opening new buffers from qf/loclist results in a small window showing the buffer, not closing the startify window

### ISSUE THREAD

**Issue by ntnn** [mhinz/vim-startify#224]
Steps to reproduce:
* open vim
* run e.g. `:make`

Expected behaviour:
* startify buffer is replaced with new buffer on first error

Actual behaviour:
* new buffer is opened in new tiny window

Example:
![example](https://ntnn.de/plain//2016-05-29_14-22_scrot.png)

Reproducable with a clean vimrc.

**Comment by mhinz** [comment]
This happens because software is terrible. ;] Buffers can have different types and Startify should certainly be no file buffer.. unfortunately that's what most often is assumed.

Should be "fixed" as of https://github.com/mhinz/vim-startify/commit/977ee633e5d8b6ea05d2c88ec06f6b7e8d67fcfb.

Thanks for mentioning it!

**Comment by ntnn** [comment]
Yup, works perfectly - thanks
