### ISSUE TITLE
Config to open file in tab by default

### ISSUE THREAD

**Issue by irliao** [mhinz/vim-startify#226]
Is there a way to override <CR> on Startify so that it opens in a new tab instead of a new buffer and without having to mark the file with 't' first?

**Comment by mhinz** [comment]
What do you want to happen exactly on what button? We can probably find a way to map it according to your needs.

E.g. a shortcut for "first mark with t, then open" doesn't make much sense, because `:edit` would behave the same as `:tabedit`, since the Startify buffer would close itself before. Nevertheless, here, this mapping would do this:

```
autocmd User Startified nmap <buffer><cr> t:call startify#open_buffers()<cr>
```

**Comment by mhinz** [comment]
@irliao \*ping\*

**Comment by mhinz** [comment]
(Feel free to reopen, if your question isn't answered yet.)

**Comment by irliao** [comment]
@mhinz Thank you so much for the response and sorry for my late response!

Your solution works perfectly!

Please relabel this issue as solved and thanks again for the help!!! :)

**Comment by mhinz** [comment]
Yay, glad to hear that. Thanks for bringing it up!
