### ISSUE TITLE
nomodifiable value in sessions.-

### ISSUE THREAD

**Issue by jimsrc** [mhinz/vim-startify#234]
Hi,
I just began using this plugin, and putted a star on it!

Before knowing about this plugin, I used the `:mksession` very often; and usually I `:set nomodifiable` with some opened files (registered in the .vim).
I began using the `:SSave` command to create the session in `~/.vim/sessions/`, but it surprised me that the opened files that were flagged with `nomodifiable` are now with `modifiable`!!

I made sure to save the session *after* setting these flags of course.
I repeated everything to make sure, because this looks very wierd to me.
Are there any default values when generating these .vim session files?
With `:mksession`, it works properly.

Thank you very much!,
Jimmy.

**Comment by mhinz** [comment]
Hi (and sorry for the late response),

Eventually `:SSave` is using `:mksession` itself, the only real difference is that startify (and almost all popular session plugins, e.g. [vim-session](https://github.com/xolox/vim-session#the-sessionoptions-setting)) unconditionally do `set sessionoptions-=options` before using `:mksession` and restoring the old value afterwards.

This is done because saving options in a session is known to often corrupt sessions in very weird ways. It's probably the #1 problem with Vim's session and the reason why using sessions in Vim is often frowned upon.

**Comment by mhinz** [comment]
Since I can't see how to solve this without opening another even bigger can or worms, I'll have to close this.

Thanks for the feedback anyway!
