### ISSUE TITLE
Opening file by key when larger than 9

### ISSUE THREAD

**Issue by TxHawks** [mhinz/vim-startify#236]
When the list files is longer than nine files, it is impossible to select files assigned a number greater than `9`. Trying to type `10` will open file `1`.

**Comment by mhinz** [comment]
Hmm, this shouldn't happen anymore. An issue like that was fixed many months ago. Not updated in a long time?

Maybe you have `'timeout'` set and `'timeoutlen'` set to a small value?

**Comment by TxHawks** [comment]
Indeed, I have `timeoutlen` set to `50`.

**Comment by mhinz** [comment]
Then there's nothing I can do about that. (Since `'timeoutlen'` is a global value, I can't just set it for the Startify buffer but would have to pay attention to all kinds of corner cases where someone leaves the buffer and reset the option.)

Are you really want such a short `'timeoutlen'`?

Or did you try to disable delays when pressing <kbd>Esc</kbd> when using tmux and the like? In that case, try `:set ttimeout ttimeoutlen=50` instead.

**Comment by TxHawks** [comment]
That worked. Thanks!
