### ISSUE TITLE
Center the intro page

### ISSUE THREAD

**Issue by n9code** [mhinz/vim-startify#248]
Add option to center the whole intro page like the original one.

**Comment by mhinz** [comment]
Sorry, but that won't happen. :-)

Absolutely everything is based on fixed columns at the moment (the UI, the cursor movement, the syntax, ...) and changing that would need quite some testing. The main problem is that, opposed to the current approach, you would have to save every line in the UI first before writing it to the buffer, because you have to know the longest line to be able to compute sane values for centering etc.

It would make the code quite a bit more complicated and since I wouldn't even use that feature myself, I kind of lack the motivation to even begin working at it. I simply don't deem this feature to be important enough to justify all the work.

I hope you understand that.

p.s. It's not the same, but at least centering the header or footer is no problem at all: `:h startify-faq-08`.

**Comment by natebass** [comment]
Keep the dream alive! I am currently trying to change formatting, maybe it is related. https://github.com/mhinz/vim-startify/issues/249
