### ISSUE TITLE
NERDTree tabs

### ISSUE THREAD

**Issue by BigfootN** [mhinz/vim-startify#271]
Hello,

I installed this [plugin](https://github.com/jistr/vim-nerdtree-tabs) in order to have NERDTree open in every tab. I looked at the faq and added:

```

autocmd VimEnter *
                \   if !argc()
                \ |   Startify
		\ |   NERDTreeTabsToggle
                \ |   wincmd w
\ | endif
```

to my `.vimrc`. Unfortunately, when starting vim I get this:

```
Error while processing VimEnter Auto commands for "*":
E488: Trailing characters: NERDTreeTabsToggle | wincmd w | endif
```
It works perfectly if I replace `NERDTreeTabsToggle` with `NERDTree`.

To be precise, I'm using `neovim v0.2.0-97gacbce46`.

Thank you very much in advance

**Comment by mhinz** [comment]
Hi,

that's a "bug" in the other plugin. The author should add `:h :command-bar` to these lines: https://github.com/jistr/vim-nerdtree-tabs/blob/master/nerdtree_plugin/vim-nerdtree-tabs.vim#L86-L94

Meanwhile, you can probably work around it using `execute 'NERDTreeTabsToggle'` instead of only `NERDTreeTabsToggle`.

**Comment by BigfootN** [comment]
Thank you very much ! `execute 'NERDTreeTabsToggle'` works like a charm !
