### ISSUE TITLE
Add support for directories in session directory.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-startify#278]
Right now if there's a directory inside of `g:startify_session_dir` Startify shows it like any other session and then complains about file not existing upon load. It would be a great feature to add support for directories where plugin could just show different menu again after "executing" directory. This way we would have better ability to organize sessions.

**Comment by mhinz** [comment]
Sorry, but that won't happen. :-)

It would make things _much_ more complicated. The plugin was never meant to show different menus and quite a bit of code would have to be rewritten to do that. And mappings have to be changed. And colours have to be re-adjusted for each new menu. And then people want to be able to go back to the previous menu and so on.

So, introducing additional menus is no option. Not because of all the code that has to be written, but because it would destroy the plugin's simple but effective way of doing things. I like simple (not easy) solutions!

If you really have a lot of sessions, then I'd suggest prefixing the session names accordingly and using `:SL <tab>` completion instead.

Or maybe there's another approach to handling lots of sessions, but I can't come up with one right now. I seldom use more than 3 sessions at the same time. I'm up for ideas here.

Anyway, thanks for the suggestion!
