### ISSUE TITLE
Relative path & use env are not working

### ISSUE THREAD

**Issue by ahmedelgabri** [mhinz/vim-startify#284]
This is my [Startify config](https://github.com/ahmedelgabri/dotfiles/blob/084ec6171958549289dc80e9310e991bd9c0f310/neovim/.config/nvim/after/plugin/startify.vim)

```vim
let g:startify_custom_header = startify#fortune#cowsay('═','║','╔','╗','╝','╚')

let g:startify_skiplist = [
      \ 'COMMIT_EDITMSG',
      \ '^/tmp',
      \ escape(fnamemodify(resolve($VIMRUNTIME), ':p'), '\') .'doc',
      \ 'bundle/.*/doc',
      \ ]

let g:startify_padding_left = 5
let g:startify_relative_path = 1
let g:startify_fortune_use_unicode = 1
let g:startify_change_to_dir = 1
let g:startify_change_to_vcs_root = 1
" let g:startify_session_autoload = 1
let g:startify_update_oldfiles = 1
let g:startify_use_env = 1

hi! link StartifyHeader Normal
hi! link StartifyFile Directory
hi! link StartifyPath LineNr
hi! link StartifySlash StartifyPath
hi! link StartifyBracket StartifyPath
hi! link StartifyNumber Title

autocmd User Startified setlocal cursorline
```

But neither of `g:startify_relative_path` or `g:startify_use_env` are working. I still see absolute paths, the config looks fine as far as I know. So I dunno what might be the reason for this?

**Comment by mhinz** [comment]
The relative path is only shown if the file is in or below the current working directory. This proved to be a good compromise, because it prevents entries like `../../../../../foo` which are not helpful at all. Showing the absolute path in those cases is much easier to grasp.

What's not working about about `g:startify_use_env`? Mind that this feature is supposed to make entries shorter.

Example:

File: `/data/github/foo`
ENV: `GH=/data/github`

This would show `$GH/foo` in Startify. If you're in `/data` already _and_ use relative paths, the env would be shown, because the path would be `github/foo` which does not match the environment variable.

**Comment by ahmedelgabri** [comment]
I understand how both work, but for some reason, none of them is working for me. I tried having just one of them at a time & it doesn't work & I tried having both (which doesn't make sense) but still doesn't work.

I always get the full absolute path with or without them being set.

**Comment by mhinz** [comment]
1. What OS are you on?
1. Please do this:
   ```
   $ vim
   :e /tmp/foo
   :w
   :cd /tmp
   :Startify
   ```

   Now, with `let g:startify_relative_path = 1` and `let g:startify_update_oldfiles = 1`, you should have
   an entry:

   ```
   [0]   foo
   ```

   Does this work or still absolute path? I'll just have to make sure that we use the exact same test. 
   The output of `:StartifyDebug` probably looks as expected in either way.

**Comment by ahmedelgabri** [comment]
1. macOS Sierra 10.12.5
2. Yes, this test worked in both vim & neovim with `let g:startify_relative_path = 1` and `let g:startify_update_oldfiles = 1`

**Comment by mhinz** [comment]
Then please give me a test case that does not work. :)

**Comment by ahmedelgabri** [comment]
Why is `0` not the same as `10`? while as you can see from the bottom I'm inside my `.dotfiles` folder.

![relative](https://cloud.githubusercontent.com/assets/63876/26559786/04d82546-44b2-11e7-8b57-ffa469197b87.png)

**Comment by mhinz** [comment]
Aha! Give me a minute.

**Comment by mhinz** [comment]
Please see if the latest version works for you.

**Comment by ahmedelgabri** [comment]
Yup this works for `let g:startify_relative_path = 1`, thanks!

But this doesn't work still `g:startify_use_env` 😬 

1. I disabled `let g:startify_relative_path = 0` & `let g:startify_use_env = 1`
2. `export FOO=~/.dotfiles/neovim/.config/nvim`
3. opened vim & now I can see the absolute URL it's not shortened to `$FOO/after/plugin/startify.vim` for example

**Comment by mhinz** [comment]
Aaah, another subtle issue! It didn't compared against the absolute path, but literally against `~/...`. When you do `FOO=~/...`, the shell expands the `~` to `/Users/ahmed`.

The code accidentally compared `/Users/ahmed/...` against `~/...`, so they would never match. (And I never noticed because i usually place all my data outside of `~`.)

**Comment by mhinz** [comment]
^ Hopefully `g:startify_use_env` works as expected now as well.

**Comment by ahmedelgabri** [comment]
Now it works, _but_ everywhere that had `~` previously is now `$HOME` is this the expected behavior? or shouldn't `$HOME` stay as `~`?

**Comment by mhinz** [comment]
^ :>

Any other default environment variables that should be ignored?

**Comment by ahmedelgabri** [comment]
Not that I'm aware of 😄 

And thank you very much!

**Comment by mhinz** [comment]
Awesome.

Thanks for bringing up all these subtle issues. :-)
