### ISSUE TITLE
Unable to resume panels started through outliners

### ISSUE THREAD

**Issue by llinfeng** [mhinz/vim-startify#289]
It seems Startify is not handling panels opened by "outliner plugins" properly. For sessions saved through Startify, should there be a side-panel created either by [VOoM](https://github.com/vim-voom/VOoM), or [vimtex](https://github.com/lervag/vimtex/), I will encounter the following errors when trying to load those sessions.

* For outlines created through `vimtex` (using the `:VimtexTocToggle` command), the error message when trying to *reopen* the session goes as:
![vimtex_toc](https://user-images.githubusercontent.com/5890407/28252964-850e7be6-6a6b-11e7-8ed6-109ff0607600.png)

* For outlines created through `VOom` (through simply `:Voom _FileType_`), the following error is present when trying to reload the session:
![vim-voom-toc](https://user-images.githubusercontent.com/5890407/28252989-ac052d94-6a6b-11e7-995f-41e0c335ed17.png)

Bypassing the errors through pressing <kbd>enter</kbd> key will yield an empty panel, with nothing restored from previous session. Also, there will be an empty buffer with 

Does this has to do with the type of panels started by the "outliner plugins"? Or, is there something native to Startify that could handle these panels.

**Comment by mhinz** [comment]
Those plugins create buffers that are not backed by files on disk. Startify basically provides wrappers around `:mksession` and `:source` for saving and loading sessions.

You can easily reproduce it like this:

```
$ vim foo.py
:Voom python
:mksession
:qa
$ vim -S Session.vim
```

(Use `:set buftype?` in the Voom buffer and it will return `nofile`.)

Do `vim Session.vim` to see what Vim is actually doing. It's really just opening buffers by path. So that's why it won't work for this kind of buffers. It _will_ create buffer for Voom (because it had a name when the session was saved), but it won't magically recreate its content.

You can tell Vim what to save on `:mksession` (or `:SSave` for that matter) by using `:h 'sessionoptions'`.

If you don't want Vim to open blank buffers when loading a session, put this in your vimrc:

```vim
set sessionoptions-=blank
```

**Comment by llinfeng** [comment]
Thank you, @mhinz! What you said makes perfect sense, and I found the following setting super helpful:

````
set sessionoptions-=blank
````

Dropping this line into my `.vimrc` saves me from attending to the errors created by those buffers that are not "backed" by a concrete file.

Unless there is a way to tell Vim to store the buffers created by "outliners" into physical files, I guess choosing not to open these "hollow buffers" is the best choice. (These buffers are hollow as they are not attached to any local files.) Will post an update if I find a way to *save* these buffers into local files.

**Comment by mhinz** [comment]
> Will post an update if I find a way to save these buffers into local files.

Vim's session feature is simply not very good. It's just a half-hearted implementation, IMHO.

Anyway, even If you find a solution, it will be very hacky and probably break in certain corner cases.

As I said, `:SSave`/`:SLoad` etc. are just really thin wrappers around `:mksession`/`:source` that assume a certain directory. This was just added so sessions can be listed at the start in the Startify buffer.

Startify is not a sophisticated session management plugin. If you really need something like that, have a look at plugins like https://github.com/xolox/vim-session. I don't know if they're really smarter than Startify in such cases, though. :-)
