### ISSUE TITLE
Colors broken in neovim

### ISSUE THREAD

**Issue by cousine** [mhinz/vim-startify#304]
Hi, I'm using neovim 0.2.2 with minpac, startify was working great (for years) however today suddenly colors are not working and I have to manually `:syntax on` even though I have syntax turned on in my vimrc/init.vim script

I tried debugging the problem but can't seem to find the problem, I also tried setting the session options as described in the FAQ but no luck there.

**Comment by mhinz** [comment]
Does it work in Vim?

There were not many changes in the last months and none of them were related to colors, so I suspect it's either an issue with your config or Neovim itself.

**Comment by mhinz** [comment]
Since I'm pretty sure it's no bug in this plugin, but rather a config issue (maybe https://github.com/neovim/neovim/issues/7365), I'm closing this.

Another advice: I know that using a release version of Nvim from a package manager is convenient, but Nvim is heavily under development. There is no release v0.2.3 yet, but there are already 1121 patches since v0.2.2, so maybe your issue is already fixed on master.

**Comment by cousine** [comment]
Pointing out neovim/neovim#7365 was helpful, though it wasn't the main issue; the problem was that I forgot to add gui color mappings to my custom `Startify` highlights, and I had `termguicolor` set.

Adding the proper guifg, guibg and gui fixed the problem 🙂

**Comment by mhinz** [comment]
D'oh. That should have come to my mind sooner.. Well, I'm glad it's solved!
