### ISSUE TITLE
SLoad saves current sessions ignoring g:startify_session_persistence = 0

### ISSUE THREAD

**Issue by alex-shamshurin** [mhinz/vim-startify#321]
Docs says that 
```
Automatically update sessions in two cases:

    1) Before leaving Vim
    2) Before loading a new session via :SLoad
```
and it's assumed it will save ONLY when `let g:startify_session_persistence = 1` but with `let g:startify_session_persistence = 0` it saves too. 

PS. I'd like to use Startify as a start screen only without session handling. This is a job for vim-obsession and vim-prosession

**Comment by mhinz** [comment]
It checks that for many years already:

https://github.com/mhinz/vim-startify/blob/4f296fe4245d7d5146bbb67d6960acd10b09d12e/autoload/startify.vim#L197-L199

I just tested it using `:SL one` (session with only one buffer), opening a few new buffers, `:SL two`, `:SL one` and I were back to the session with only one buffer. So the session wasn't altered.

**Comment by alex-shamshurin** [comment]
Hmm, here is my scenario:

1. Startify is a first screen
2. VIM-obsession write sessions and keeps it in sync state (always, not only on exit and before switching)
3. VIM-prosession I use to create new session by specifying a path and previously I used this plugin to autoload last session when vim was started from user's home dir (MacVim, GVIM are started from home, user starts gvim by just clicking on icon). Prosession also handles that there is only one session inside project.
4. ctrlp-obsession gives me a nice way to switch sessions

(It will be great if only one did the the job). 

Problem: So when I switch sessions via ctrlp-obsession - everything is fine. But when I use `SLoad` I always get an empty session, SLoad corrupt it somehow (Actually I use SLoad only to test vim-startify, normally I use ctrlp-obsession)

**Comment by mhinz** [comment]
The code for `:SLoad` is pretty simple and I'm fairly sure it doesn't corrupt anything by itself. (Unless you have actual exact steps that reproduce the problem when the other session plugins are disabled.)

I can think of only one thing at the moment.. let's try this in your vimrc:

```vim
let g:startify_session_delete_buffers = 0
```

Does this solve your issue already?

**Comment by alex-shamshurin** [comment]
It changes something - sessions are not empty any more, new session is loaded, but old session buffers were not closed, so I got a mix of two sessions. The expected behaviour of `g:startify_session_delete_buffers` was to clean up the buffers list ob startify page itself (this is how I understood it).

**Comment by mhinz** [comment]
No, it deletes all your current buffers, so that you only get the buffers of the session after `:SLoad`.

When that happens, if deletes a buffer, switches to the next one, deletes a buffer, switches to the next one etc. Everytime that happens, the `BufEnter` event is triggered and vim-obsession saves the session: https://github.com/tpope/vim-obsession/blob/master/plugin/obsession.vim#L118

So.. when doing `:%bdelete`, you end up with an empty session. From Startify's side everything works as expected, it's just that both plugins use different approaches to session handling that don't play well together.

Putting it in a nutshell, I see two things to avoid this issue:

1. Using `let g:obsession_no_bufenter = 1`
1. Changing this plugin no to trigger any events when deleting all buffers. But there might be some use cases for this, and I'm reluctant to do this just to make it work together with another plugin for session handling.

But since you don't want to use startify's session handling, there should be no problem anyway, eh?

**Comment by alex-shamshurin** [comment]
I'd like to stick to one plugin and use one instead of 3. Startify gives nice start page like IDE, but it doesn't save all the time current state (only on SLoad and vim exit) and does not let me create new session.

**Comment by mhinz** [comment]
> but it doesn't save all the time current state

When is this a problem?

When you work in a session, you do that until you exit the editor or switch to another session (with `:SLoad`) or close the session (with `:SClose`). In all these cases your session gets saved.

> does not let me create new session

Just close the current session with `:SClose` (note how `:echo v:this_session` is empty afterwards), open any buffers you want and save them with `:SS newsession`.
