### ISSUE TITLE
Markers for Funcref type

### ISSUE THREAD

**Issue by VladimirPal** [mhinz/vim-startify#328]
Hi!
How can i have an ability to use markers(s,b v) in Funcref type.
for example i have an function:
```vim
function! s:list_modified()
  let files = systemlist('git ls-files -m')
  return map(files, '{"line": v:val, "cmd": "edit ". v:val }')
endfunction

let g:startify_lists = [
  \ { 'type': function('s:list_modified), 'header': ['Modified'] },
\ ]
```

Do you have an function which i can use for it?
Thanks.

**Comment by mhinz** [comment]
You mean so that `v` would split the window vertically etc. even for funcrefs?

I'd like to avoid introducing another key (besides `line` and `cmd`), but we could change `cmd` so that if it contains a valid path (instead of a command), use the marker type for opening it.

I'll hack up a PoC later today!

**Comment by mhinz** [comment]
Please update the plugin and change one line in your example:

```vim
return map(files, '{"line": v:val, "path": v:val }')
```

If it works for you, I'll add it to the documentation.

**Comment by VladimirPal** [comment]
Works like a charm.
Thank you.

**Comment by VladimirPal** [comment]
If the function returns an empty list it will cause the error, I've fixed in the PR.
