### ISSUE TITLE
git commands don't run inside startify

### ISSUE THREAD

**Issue by bling** [mhinz/vim-startify#33]
i use fugitive and gitv a lot, and frequently i'll start up vim and then do a `:Gstatus` or `:Gitv` to look up on git related stuff.  however, the commit 53019cc309c3bc165e04c1a092832500ce41ae92 broke this workflow; specifically, the `enew` call.

i deleted that line and don't notice anything funky...and the commands started working again.

**Comment by blueyed** [comment]
For what it's worth, the error is e.g. "E492: Not an editor command: Gstatus" and the order of fugitive and startify is important: fugitive has to be loaded after startify - otherwise fugitive's VimEnter gets called on the buffer which is not startified yet.

Maybe this regressed in 4a788df9, where "enew" was added again(?).

**Comment by mhinz** [comment]
It was changed back then because of the complicated way for detecting the calling buffer which was changed afterwards.. so the `:enew` isn't useful anymore at start anymore.

Thanks for spotting!

**Comment by blueyed** [comment]
Thanks for fixing it!
