### ISSUE TITLE
Bug with system cmd in custom header quotes

### ISSUE THREAD

**Issue by Titubery** [mhinz/vim-startify#396]
I just copied your code from #285 to my .vimrc :
`let g:startify_custom_header_quotes = [ {-> systemlist('date')} ]`
Howerver, that didn't work but only showed some ERROR messsage🙃️:
![quote](https://user-images.githubusercontent.com/17917040/67622537-948dc500-f84d-11e9-9e97-7f00cff9dc7f.png)
What's wrong with it?😭️
By the way, thanks  for your works!

**Comment by mhinz** [comment]
Thanks! Should be fixed now. :)

**Comment by kajmaj87** [comment]
I'm encountering the same issue on the newest master version:

![obraz](https://user-images.githubusercontent.com/1036795/215833738-7e034757-c92d-4ccc-ae04-4d82a2b7b48a.png)

This is with config like this:

![obraz](https://user-images.githubusercontent.com/1036795/215833845-143ea0d5-8f0d-42d9-8e1c-0b87bae00767.png)

I wanted to eventually use the vim-tips like this:

`let g:startify_custom_header_quotes = [ {-> readfile('~/.vim/vimtips.txt')} ]` 

but this also does not work because of the same error.

I'm using:
`VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 19 2022 04:59:57)`

**Comment by kajmaj87** [comment]
@mhinz Is it possible to reopen the issue?
