### ISSUE TITLE
(neo)vim Startuptime in footer

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [mhinz/vim-startify#404]
I'd like to display the startup time in the footer and I'm not sure how to go about it. 

I read in the docs about using the output of a command, so I tried

```vim
redir => test
    silent nvim --startuptime /dev/stdout -c quit 
redir END

let g:startify_custom_footer =
    \ map(split(test), 'repeat(" ", 10) . v:val')
```
but I get an error saying it's not an editor command.

I think Ideally I'd use [startuptime.vim](https://github.com/tweekmonster/startuptime.vim) and get the first 15 lines and then below it echo "Please run :StartupTime for more details"

So I'd get something like this
```vim
Startup Time
Total Time:   21.910 -- Flawless Victory


Slowest 10 plugins (out of 22)~
     [runtime]	5.757   
space-vim-dark	4.097   
  vim-polyglot	2.998   
      coc.nvim	2.957   
       [vimrc]	2.352   
  vim-devicons	1.091   
           ale	0.692   
 spaceline.vim	0.424   
 vim-gutentags	0.395   
     ultisnips	0.333   

Please run :StartupTime for more details
```

**Comment by mhinz** [comment]
`silent nvim` would look for a `:nvim` command, which does not exist. If you want to shell out, use `silent !nvim`. Or just `let test = execute('nvim --startuptime /dev/stdout -c quit')` instead of using `:redir`.

But think about it: If you start nvim it runs startify which runs nvim which runs startify which runs nvim... and so on. This sounds like a bad idea. ;-)

I don't use startuptime.vim, so I can't say anything about it.

But when you're testing the startup time, you probably want to improve it. That's usually something you do once, when you're using a lot of plugins or to find a slow one. By starting two nvim processes each time you effectively slow down what you're trying to speed up in the first place.
