### ISSUE TITLE
How Do I Empty MRU List?

### ISSUE THREAD

**Issue by y1rah** [mhinz/vim-startify#418]
Hey guys, recently I've been used vim-startify and spent a decent time on it.

Here is a question, seems that MRU list is kinda cache stored somewhere, traveling from dirs to dirs, I do not always find previous file list helpful but sometimes discouraging.

Is there any ways to clear or empty whole or some of the items in MRU list?

Thanks. ^_^

**Comment by mhinz** [comment]
The plugin simply uses the builtin `v:oldfile` variable that is fed on Vim startup by your viminfo (or shada file with Nvim).

E.g. you won't get any entries when you start Vim like this `vim -i NONE`.

Also have a look at `:h g:startify_update_oldfiles`.

You can use VimL to set `v:oldfiles` to anything you want. E.g.

```
:let v:oldfiles = ['~/.vim/vimrc']
:Startify
```

This should only show the above file now (or nothing when the file doesn't exist, because Startify filters non-existing entries).

Hope this helps!
