### ISSUE TITLE
Not showing buffers on restoring a saved session using lightline. 

### ISSUE THREAD

**Issue by TanishBansal** [mhinz/vim-startify#431]
Not showing buffers on restoring a saved session using mengelbrecht/lightline-bufferline and it shows up when I switch to another buffer but the order saved it was saved in is not preserved.

**Comment by mhinz** [comment]
Startify is eventually just using `:source path/to/sessionfile` to restore a session. You can test that yourself. (See `:h g:startify_session_dir` for where to find the session files.) No magic involved.

And from what I can tell from your description, the session itself is sourced just fine, it's just lightline-bufferline that isn't updating unless you switch the buffer.

So, the issue is most probably in lightline-bufferline. Please create an issue for lightline-bufferline instead.
