### ISSUE TITLE
Quick question: Location of let g:startify_disable_at_vimenter

### ISSUE THREAD

**Issue by reportaman** [mhinz/vim-startify#457]
Am using [vim-plug](https://github.com/junegunn/vim-plug) plugin manager, should I set `let g:startify_disable_at_vimenter = 1` before or after loading `Plug mhinz/vim-startify`? Both yield similar visual result, my question is more rooted in performance... the few milliseconds that can be saved (it builds up in vimrc :D)

**Comment by mhinz** [comment]
Performance-wise it should make no difference at all! By the time any file from vim-startify is read, the vimrc was completely sourced already.

It doesn't matter where the `Plug` lines are, because these plugins are _not_ read immediately. vim-plug merely adjusts the runtimepath (see `:h 'rtp'`), which makes the plugins part of the runtime that is sourced according to certain rules _after_ vimrc was read (`:h startup`).

(Also check the sourcing order via `:scriptnames`.)

Personally I have all my `Plug` lines at the top of the vimrc and all options at the bottom. It's really about personal taste. :-)
