### ISSUE TITLE
Extra 'Press ENTER' prompt when guioptions contain '!'

### ISSUE THREAD

**Issue by fedorenchik** [mhinz/vim-startify#460]
Actual behaviour:
After setting:
`:set guioptions+=!`
when saving session (SSave!) or restoring session from startify buffer, there will be extra
`Press ENTER or type command to continue` prompt.
Without `:set guioptions+=!` there isn't such prompt.
Expected behaviour:
No matter what's in `guioptions`, there should not be `Press ENTER or type command to continue` prompt.

**Comment by mhinz** [comment]
Do you happen to use gvim on Linux?

**Comment by mhinz** [comment]
I could reproduce the `Press ENTER` prompt with `call system('echo foo')`, if `guioptions+=!` is set. So, a simple `:silent` should fix it, since we're not interested in the output.

`system()` is only used once in the plugin, to create the "last session link" on Unix-like systems, so that `:SL!` can be used.

**Comment by fedorenchik** [comment]
> Do you happen to use gvim on Linux?
Yes.

Thank you.
