### ISSUE TITLE
Add other standard maps to edit new empty buffer

### ISSUE THREAD

**Issue by fedorenchik** [mhinz/vim-startify#463]
Startify already supports `i` and `<insert>` to open and edit new buffer.
It would be nice to also support `I`, `a`, `A`, `o`, `O`.

**Comment by mhinz** [comment]
Unfortunately, that's very subjective. :-)

In my experience, having many default mappings is a bad thing (even more so when having multiple mappings for one thing), because then someone else will create another issue that the new defaults interfere with his mappings etc.

Long story short: `autocmd User Startified nmap <buffer> I i` etc. 

Thanks anyway!
